debug: true
spring:
  application:
    name: college_management_system
  profiles:
    active: dev
  flyway:
    enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
