debug: true
spring:
  datasource:
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${DATABASE_URL}/${DATABASE_NAME}?useSSL=false
    username: ${DATABASE_USER_NAME}
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: validate
