debug: true
spring:
  datasource:
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${DATABASE_URL}/${DATABASE_NAME}?useSSL=false
    username: ${DATABASE_USER_NAME}
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
