debug: false
spring:
  application:
    name: college_management_system
  datasource:
    password: aaqwe123@P
    url: jdbc:postgresql://localhost:5432/college_management_system_db?useSSL=false
    username: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
        ddl-auto: update
server:
  port: 8081
